### PR TITLE
Workspace/Project Settings

### PR DESCRIPTION
**Pull request by itsjoeoui**
Also nuked the nextjs app as the new platform is getting stable now...

### CODE REVIEW

**Review by LatentDream — CHANGES_REQUESTED** [review]
## TODO

- [ ] Better toast error msg
- Creating a part while being a member: toast with internal server error!
- Creating a part while being a member: toast with forbidden

### Workspace

- [x] At first, I though the invite was by email, maybe change the toast message to say where the invite is (The invite process is cool btw)
- [x] No Access to the Unit page
- [x] Adding a way to know if you are an owner, admin or member (workspace role)
- [x] `Delete workspace` only for the owner
- [x] Blocking Self-Invite (and re-invite if already in)

### Prod Line

- [ ] Prod line settings page
- [ ] No Access to the Session page
- [ ] I can't say for the Measurement page
- [ ] Adding a way to know your project role as well
- [ ] Prod line are not shared between user

## Will do in separate PRs
- Soft-delete of workspace ?
- We can’t cancel an invitation (could be in another issue)

**Review by LatentDream — CHANGES_REQUESTED** [review]
- [x] Mouse over click symbol on the join workspace badge.
- Question: should we add, "add to a production line" at the same time of the invite. So an admin doesn't have to wait for the user to accept. 
- Not related, but in an instance `No test sessions found, go upload one using the test sequencer in Flojoy Studio!`. Link to download Studio :)
- [x] Production Line page: since the `dev` / `test` can't invite people, remove the settings on the page or toast that say they can't do this action, refer to the workspace admin `...@....com`. Right now, the user will think he can invite people
- [x] Production Line Setting: `dev -> developer` `test -> operator`

**Comment by itsjoeoui** [comment]
> * [x]  Mouse over click symbol on the join workspace badge.
> * Question: should we add, "add to a production line" at the same time of the invite. So an admin doesn't have to wait for the user to accept.
> * Not related, but in an instance `No test sessions found, go upload one using the test sequencer in Flojoy Studio!`. Link to download Studio :)
> * [ ]  Production Line page: since the `dev` / `test` can't invite people, remove the settings on the page or toast that say they can't do this action, refer to the workspace admin `...@....com`. Right now, the user will think he can invite people
> * [ ]  Production Line Setting: `dev -> developer` `test -> operator`

@LatentDream actually a `dev` can invite people too!

**Review by LatentDream — APPROVED** [review]

**Comment by LatentDream** [comment]
** Approved** feature wise

**Review by 39bytes — APPROVED** [review]

**Pull request merged**
